server:
  #设置tomcat 端口号
  port: 8989
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ems?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    #mybatis:
    #  mappers-locations: classpath:com/baizhi/ems/ytz/mappers/*.xml
    #  type-aliases-package: com.baizhi.ems.ytz.domain
  jpa:
    show-sql: true
    database: mysql
  thymeleaf:
    cache: false
    prefix: classpath:/templates/ #添加路径前缀
    mode: HTML5
    encoding: UTF-8
    suffix: .html


